services:
  analysis_panel:
    image: 703178115275.dkr.ecr.us-west-2.amazonaws.com/analysis_panel:v1
    ports:
      - "8500:8501"
    env_file:
      - D:/Development/Projects/finance/stock_analysis_panel/.env
    volumes:
      - D:/Development/Projects/finance/stock_analysis_panel/data:/srv/stock_analysis_panel/data
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - D:/Development/Projects/finance/stock_analysis_docker/nginx/server.pem:/etc/nginx/ssl/server.pem
      - D:/Development/Projects/finance/stock_analysis_docker/nginx/server.key:/etc/nginx/ssl/server.key
      - D:/Development/Projects/finance/stock_analysis_docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    env_file:
      - D:/Development/Projects/finance/stock_analysis_panel/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge